### ISSUE TITLE
addViewInLayout不是必调用的方法

### ISSUE THREAD

**Issue by naruto-wbb** [kelinZhou/Banner#1]
ViewPager 中
    public void addView(View child, int index, ViewGroup.LayoutParams params) {
        if (mInLayout) {
            if (lp != null && lp.isDecor) {
                throw new IllegalStateException("Cannot add pager decor view during layout");
            }
            lp.needsMeasure = true;
            addViewInLayout(child, index, params);
        } else {
            super.addView(child, index, params);
        }
}

BannerView父类为FrameLayout时不会调用

**Comment by kelinZhou** [comment]
谢谢你，我使用了这么久一直没有发现这个问题，感谢你提出的Issues，我已经在2.2.1版本修复。再次感谢。
