### ISSUE TITLE
你这东西过于复杂吧

### ISSUE THREAD

**Issue by mosentest** [kelinZhou/Banner#10]
@Override
    public boolean same(BannerEntry newEntry) {
        return newEntry instanceof TitleImageBannerEntry && TextUtils.equals(title, newEntry.getTitle()) && TextUtils.equals(subTitle, newEntry.getSubTitle()) && imgRes == ((TitleImageBannerEntry)newEntry).imgRes;
    }

**Comment by kelinZhou** [comment]
不知道你说的过于复杂的意思是?

**Comment by kelinZhou** [comment]
如果你觉得复杂，你也可以使用equals方法。

**Comment by kelinZhou** [comment]
或则您有什么更好的方式来实现这个逻辑您也可以提供给我，不胜感激。

**Comment by mosentest** [comment]
这东西你自己内部实现比较URL就好了，抽出一个接口 传url的value

**Comment by kelinZhou** [comment]
不好意，最近工作忙，在加上老婆刚刚生。刚刚有时间解决这个问题。已在SimpleBannerEntry中对same做了默认实现。并将same方法更名为theSame。会在2.6.0之后的版本更新。感谢您的宝贵意见。
