### ISSUE TITLE
圆点指示器没有空心属性

### ISSUE THREAD

**Issue by qinhuangran** [kelinZhou/Banner#11]
UI中有些圆点指示器要求空心圆环的

**Comment by kelinZhou** [comment]
实在抱歉，这么久才来处理你的issues。最近工作太忙了，以及老婆刚刚生了Baby，请谅解。您的需求已完成，将会在3.6.0之后的版本中更新。

**Comment by kelinZhou** [comment]
抱歉说错了，是2.6.0之后的版本(2.7.0版本开始支持)
