### ISSUE TITLE
请问，如果想把banner的title设置为从网络上动态加载，应该怎么弄。

### ISSUE THREAD

**Issue by hans0090** [kelinZhou/Banner#12]
请问可以用什么方法。我自己考虑半天，都有点糊涂了。

**Comment by kelinZhou** [comment]
本来就是从网络上获取的呀。就像你图片的url一样。还是我理解的不对。如果理解的不对，麻烦你描述的更加详细一点。

**Comment by hans0090** [comment]
是这样的，我看到所有url和title都是在这个方法中添加的  
 private List<TitleImageBannerEntry> getTitleImageBannerEntry(){    } ；
如果我新开启一个线程，然后从网上得到title和url的字符串，然后再调用
bannerView.setEntries(getImageBannerEntries());
就会直接闪退，并且报错；
java.lang.RuntimeException: You need called the setEntries method!

也就是说，bannerView.setEntries(getImageBannerEntries());必须在onstart的时候立即调用，但是网络加载需要时间，所以会出错。

我看到很多app都是有一个guide，启动app之后等待一段时间再到主界面，我想问一下url和title是不是要在guide里面加载。不能在主界面直接加载？

**Comment by kelinZhou** [comment]
你加一下我的微信吧，kelinZQL。

**Comment by kelinZhou** [comment]
不是你说的这么回事儿，setEntries被调用之前你就去调用selectCenterPage去手动选中某个Banner页，当然不行啊，本着防御式编程的原则所以我这里抛出一个异常。就是为了告诉你这么调用是不对的。但是可能我提示的不够明白，我后面会改成You need to call the 'setEntries' method before calling the 'selectCenterPage' method!
