### ISSUE TITLE
BannerView 如果内容集合只有一条数据的时候，setOnPageClickListener 点击无效

### ISSUE THREAD

**Issue by zhankong** [kelinZhou/Banner#13]
BannerView的setOnPageClickListener事件，可以再优化下。如题，只有一条数据的时候点击无效

**Comment by kelinZhou** [comment]
好的，感谢。现在身边没有电脑，明天我看一下。发自我的华为手机-------- 原始邮件 --------发件人： zhankong <notifications@github.com>日期： 2020年8月4日周二 下午3:43收件人： kelinZhou/Banner <Banner@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [kelinZhou/Banner] BannerView 如果内容集合只有一条数据的时候，setOnPageClickListener 点击无效 (#13)

BannerView的setOnPageClickListener事件，可以再优化下。如题，只有一条数据的时候点击无效

**Comment by zhankong** [comment]
谢谢，期待您的结果

**Comment by kelinZhou** [comment]
我测试过了  并没有发现你说的问题，如果你仍然有问题可以加我微信：kelinZQL。
