### ISSUE TITLE
请问条形指示器这里要怎么写

### ISSUE THREAD

**Issue by HH-Ding** [kelinZhou/Banner#14]
我看指示器都是右置的圆点和数字指示器，请问你这个项目里写居中的条形指示器要怎么写，不是很懂，望赐教

**Comment by kelinZhou** [comment]
再您提出Issues时还不支持条形指示器，需要您自己定义。不过在2.9.0版本之后增加了[LineIndicatorView](https://github.com/kelinZhou/Banner/blob/master/banner/src/main/java/com/kelin/banner/view/LineIndicatorView.java)用来绘制条形指示器。如何使用可[参考文档](https://github.com/kelinZhou/Banner#lineindicatorview-%E7%9A%84%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B1%9E%E6%80%A7)。
