### ISSUE TITLE
怎么在xml中配置不自动轮播

### ISSUE THREAD

**Issue by chenyuethan** [kelinZhou/Banner#2]

**Comment by kelinZhou** [comment]
默认是不会启动轮播的，需要轮播就要调用bannerView.start()。
bannerView.setEntries(bannerEntries)默认会掉用bannerView.start()
如果你不希望自动轮播则可以调用它重载方法，bannerView.setEntries(bannerEntries, false)。
```
//设置数据源并开始轮播。如果不希望启动轮播则调用两个参数的方法：bannerView.setEntries(bannerEntries, false); 你也可以通过bannerView.start();的方式启动轮播。
bannerView.setEntries(bannerEntries);
```

Xml中只能配置轮播方式，通过BannerView的loopMode属性配置：

app:loopMode 配置轮播模式，该属性为枚举属性，有以下三个值可以配置：

1. infiniteLoop 无限循环轮播。
2. fromCoverToCover 从第一页轮播到最后一页，然后停止轮播。
3. fromCoverToCoverLoop 从第一页轮播到最后一页，然后再回到第一页后再轮播到最后一页，一直重复。
