### ISSUE TITLE
出现闪烁

### ISSUE THREAD

**Issue by cleVSokc** [kelinZhou/Banner#3]
大神，有个问题，从最后一页划到第一页时，第一页有个闪烁的bug，，不管是自动轮播还是手动都有闪烁，但是从第一页划到最后一页则没有。看了你的demo也没有这个问题啊 ，求赐教

**Comment by kelinZhou** [comment]
是最新的代码吗？如果你是最新的代码，把你的操作录一个屏发到我的邮箱里。或者是QQ6067429。
