### ISSUE TITLE
无限轮播有时候会停止

### ISSUE THREAD

**Issue by Kunsan16** [kelinZhou/Banner#4]
四张图，有时候会停在最后一张，不再重复轮播

**Comment by kelinZhou** [comment]
你说的这种现象我没有曾经修复过。目前我自己的项目中没有遇到过你说的问题。
麻烦你把版本号以及复现步骤说一下  以便我解决问题。谢谢。

**Comment by Kunsan16** [comment]
中间大两边小的轮播图
息屏一会，回来后，发现轮播图停留在最后一张，右边空白了，没有下一张

**Comment by Kunsan16** [comment]
手动start  和 pause 解决问题了

**Comment by kelinZhou** [comment]
请问一下你的代码是最新的吗？你说的这些问题我早就已经修复了。麻烦提供一下你当前代码的commit号，以及bug截图，以帮助我修复问题。谢谢！
