### ISSUE TITLE
是不是没有自定义指示器的功能

### ISSUE THREAD

**Issue by shenggaofei** [kelinZhou/Banner#8]
比如L自定义椭圆形的指示器

**Comment by kelinZhou** [comment]
你可以实现Pageable接口或继承BannerIndicator抽象类实现自己的指示器。如果你使用的是第三方的指示器你可以通过继承然后实现Pageable接口来做。反正最终你的指示器必须是Pageable的子类。只要你是Pageable的子类就可以通过在Xml布局文件中配置的方式使用。

如果你认为实现Pageable接口有写困难你也大可不必实现Pageable接口，你可以在代码中监听BannerView的滑动，然后在某一个页面被选中后手动通过代码设置及的指示器即可。

如果我的解答解决了你的问题请回复我，以便我关闭这条Issues。感谢。
