### ISSUE TITLE
无限轮播有时会停止

### ISSUE THREAD

**Issue by HH-Ding** [kelinZhou/Banner#9]
特别是锁屏后这个复现几率很高

**Comment by kelinZhou** [comment]
你的问题我收到了，只是我最近在忙工作的事情。一但我有了时间会第一时间解决这个问题。希望你能留下你的邮箱或其他的联系方式。以便我在修复问题后及时的通知你。感谢。

**Comment by HH-Ding** [comment]
大神辛苦了～请先忙好工作的事情，年底了，任务很正常。我的邮箱是：1724555872@qq.com&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kelin"<notifications@github.com&gt;; 
发送时间: 2019年12月25日(星期三) 晚上11:41
收件人: "kelinZhou/Banner"<Banner@noreply.github.com&gt;; 
抄送: "炸蛋炒丁"<1724555872@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kelinZhou/Banner] 无限轮播有时会停止 (#9)




你的问题我收到了，只是我最近在忙工作的事情。一但我有了时间会第一时间解决这个问题。希望你能留下你的邮箱或其他的联系方式。以便我在修复问题后及时的通知你。感谢。

**Comment by kelinZhou** [comment]
你好，请问一下你出现问题的设备信息能告诉我吗？比如手机品牌 系统版本 以及Android版本等。我自己也一直在使用包括我昨天也进行了测试，并没有复现出你描述的问题。哦，还有麻烦你告诉我一下你所依赖的Banner库的版本号。感谢。

**Comment by HH-Ding** [comment]
华为mate 20,系统版本10.0，小米8，9.0. oppo R15 8.1.0都出现过。基本是，显示了轮播图那个界面后，切换到其他界面或者锁屏，或者暂时退入后台，大概等一段时间，再返回来，就有概率出现这个问题，右边的是空的。我往左滑一下就又可以轮播



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kelin"<notifications@github.com&gt;; 
发送时间: 2019年12月26日(星期四) 中午12:00
收件人: "kelinZhou/Banner"<Banner@noreply.github.com&gt;; 
抄送: "炸蛋炒丁"<1724555872@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kelinZhou/Banner] 无限轮播有时会停止 (#9)




你好，请问一下你出现问题的设备信息能告诉我吗？比如手机品牌 系统版本 以及Android版本等。我自己也一直在使用包括我昨天也进行了测试，并没有复现出你描述的问题。哦，还有麻烦你告诉我一下你所依赖的Banner库的版本号。感谢。

**Comment by kelinZhou** [comment]
那你依赖我的库的版本是多少？Sent from my Huawei phone-------- Original message --------From: HH-Ding <notifications@github.com>Date: Thu, Dec 26, 2019, 2:54 PMTo: kelinZhou/Banner <Banner@noreply.github.com>Cc: Kelin <kelin410@163.com>, Comment <comment@noreply.github.com>Subject: Re: [kelinZhou/Banner] 无限轮播有时会停止 (#9)华为mate 20,系统版本10.0，小米8，9.0. oppo R15 8.1.0都出现过。基本是，显示了轮播图那个界面后，切换到其他界面或者锁屏，或者暂时退入后台，大概等一段时间，再返回来，就有概率出现这个问题，右边的是空的。我往左滑一下就又可以轮播







------------------&nbsp;原始邮件&nbsp;------------------

发件人: "Kelin"<notifications@github.com&gt;; 

发送时间: 2019年12月26日(星期四) 中午12:00

收件人: "kelinZhou/Banner"<Banner@noreply.github.com&gt;; 

抄送: "炸蛋炒丁"<1724555872@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 

主题: Re: [kelinZhou/Banner] 无限轮播有时会停止 (#9)









你好，请问一下你出现问题的设备信息能告诉我吗？比如手机品牌 系统版本 以及Android版本等。我自己也一直在使用包括我昨天也进行了测试，并没有复现出你描述的问题。哦，还有麻烦你告诉我一下你所依赖的Banner库的版本号。感谢。

**Comment by kelinZhou** [comment]
这样吧，你加我一下微信吧。kelinZQL  这是我的微信号。Sent from my Huawei phone-------- Original message --------From: HH-Ding <notifications@github.com>Date: Thu, Dec 26, 2019, 2:54 PMTo: kelinZhou/Banner <Banner@noreply.github.com>Cc: Kelin <kelin410@163.com>, Comment <comment@noreply.github.com>Subject: Re: [kelinZhou/Banner] 无限轮播有时会停止 (#9)华为mate 20,系统版本10.0，小米8，9.0. oppo R15 8.1.0都出现过。基本是，显示了轮播图那个界面后，切换到其他界面或者锁屏，或者暂时退入后台，大概等一段时间，再返回来，就有概率出现这个问题，右边的是空的。我往左滑一下就又可以轮播







------------------&nbsp;原始邮件&nbsp;------------------

发件人: "Kelin"<notifications@github.com&gt;; 

发送时间: 2019年12月26日(星期四) 中午12:00

收件人: "kelinZhou/Banner"<Banner@noreply.github.com&gt;; 

抄送: "炸蛋炒丁"<1724555872@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 

主题: Re: [kelinZhou/Banner] 无限轮播有时会停止 (#9)









你好，请问一下你出现问题的设备信息能告诉我吗？比如手机品牌 系统版本 以及Android版本等。我自己也一直在使用包括我昨天也进行了测试，并没有复现出你描述的问题。哦，还有麻烦你告诉我一下你所依赖的Banner库的版本号。感谢。
